!****************************************************************************************************
!这是原子有限元的子程序，作用在于将C、Si原子位置数据保存至文件，输入格式和数据如下：
!
!读入变量（input）：
!
!输出变量（output）：
!
!新建变量（new）：
!
!调用子程序（函数）：
!
!被调用子程序（函数）：
!
!读写文件名：
!
!****************************************************************************************************
subroutine initial_data_gro_output(number_x, number_y, number_z, number_real, position)
!
implicit none
!
	integer(kind=4) number_x, number_y, number_z, number_real, i, j
	real(kind=8) position(3,number_real)
    real(kind=8) x,y,z
	character(len=4) nodetype
!
!  
    
    open(1,file='output.gro')
    
    nodetype='Si'
	!write(1,"(a,i3,x,a,i3,x,a,i3)")'Generated by carbon_generate code. Powered by dhl'
    write(1,"(a,i3,x,a,i3,x,a,i3)")'Generated by carbon_generate code. Powered by dhl'
    write(1,"(I10)") number_real
    
	i = 1
	do j=1, number_real
        write(1,"(I5,A5,A5,I5,3F8.3,3F8.4,/)") i, 'Si_m', nodetype, j, position(:,j)
		!write(1,9) i, 'Si_m', nodetype, j, position(:,j)
	enddo
	x=10.0;y=10.0;z=10.0
	write(1,"(3F)")x,y,z
    close(1)

end subroutine initial_data_gro_output